version: "3.7"
services:
    
    # This redis is setup without auth
    # this is just for local testing
    deblurring-redis:
        image: redis:latest
        ports:
            - 7001:6379
        container_name: deblurring-redis

    deblurring-database:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: deblurrer
        ports:
            - 6543:5432
        container_name: deblurring-database

    deblurring-backend:
        build: .
        image: deblurring-backend:latest
        ports:
            - 8000:8000
        volumes:
            - .:/deep-deblurring-backend
        depends_on:
            - deblurring-database
            - deblurring-redis
        container_name: deblurring-backend

