version: "3.7"
services:

    deblurring-database:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: deblurrer
        ports:
            - 5432:5432
        networks: 
            - deep-deblurring
        container_name: deblurring-database

    deblurring-backend:
        build: .
        image: deblurring-backend:latest
        ports:
            - 8000:8000
        networks:
            - deep-deblurring
        volumes:
            - .:/deep-deblurring-backend
        depends_on:
            - deblurring-database
        container_name: deblurring-backend
    
networks:
    deep-deblurring:
        external: true
